theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true